### ISSUE TITLE
CreatureAsset calls CreateTemplate in constructor

### ISSUE THREAD

**Issue by Alexejhero** [LeeTwentyThree/ECCLibrary#3]
![image](https://github.com/LeeTwentyThree/ECCLibrary/assets/32238504/e9645888-a4d4-4ae0-a14c-96700ae2cdd2)

If an instance of a class extending CreatureAsset is created, the CreatureAsset constructor will be called before the constructor of the derived class, so the call to CreateTemplate will be made before the constructor of the derived class is called, which will cause problems.

This is different from the version of ECCLibrary that you gave me the download to (the zip file from the SN modding discord), where this.Template was NOT assigned in the constructor.

https://www.jetbrains.com/help/rider/VirtualMemberCallInConstructor.html

---

I ran into this issue because my derived class takes in a prefab as a constructor parameter which it then assigns to a property to be used in CreateTemplate.

![image](https://github.com/LeeTwentyThree/ECCLibrary/assets/32238504/cdcec9ac-98b5-429e-906b-bbc821738fb0)

However, since CreateTemplate is called before the actual constructor is called, this leads to the prefab being null.

One possible solution would be reassigning this.Template before calling Register, but that also can't be done because Template is init-only

So the workaround is this

 
![image](https://github.com/LeeTwentyThree/ECCLibrary/assets/32238504/d8a3d659-f0c4-4c75-a59a-b1823f5449f6)

**Comment by 32Kallies** [comment]
Fixed
